#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MyWebsite")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_item(tbl_item instance);
    partial void Updatetbl_item(tbl_item instance);
    partial void Deletetbl_item(tbl_item instance);
    partial void Inserttbl_item_category(tbl_item_category instance);
    partial void Updatetbl_item_category(tbl_item_category instance);
    partial void Deletetbl_item_category(tbl_item_category instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MyWebsiteConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_item> tbl_items
		{
			get
			{
				return this.GetTable<tbl_item>();
			}
		}
		
		public System.Data.Linq.Table<tbl_item_category> tbl_item_categories
		{
			get
			{
				return this.GetTable<tbl_item_category>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_item")]
	public partial class tbl_item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private System.Nullable<int> _parent;
		
		private string _detail_short;
		
		private string _detail;
		
		private string _subject;
		
		private System.Nullable<long> _price;
		
		private System.Nullable<long> _promotion_price;
		
		private string _image;
		
		private System.Nullable<byte> _status;
		
		private System.Nullable<byte> _hot;
		
		private System.Nullable<int> _sort;
		
		private System.Nullable<int> _view_amount;
		
		private System.Nullable<int> _buy_amount;
		
		private System.Nullable<System.DateTime> _date_added;
		
		private System.Nullable<System.DateTime> _last_modified;
		
		private string _titile;
		
		private string _description;
		
		private string _keyword;
		
		private EntityRef<tbl_item_category> _tbl_item_category;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnparentChanging(System.Nullable<int> value);
    partial void OnparentChanged();
    partial void Ondetail_shortChanging(string value);
    partial void Ondetail_shortChanged();
    partial void OndetailChanging(string value);
    partial void OndetailChanged();
    partial void OnsubjectChanging(string value);
    partial void OnsubjectChanged();
    partial void OnpriceChanging(System.Nullable<long> value);
    partial void OnpriceChanged();
    partial void Onpromotion_priceChanging(System.Nullable<long> value);
    partial void Onpromotion_priceChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnstatusChanging(System.Nullable<byte> value);
    partial void OnstatusChanged();
    partial void OnhotChanging(System.Nullable<byte> value);
    partial void OnhotChanged();
    partial void OnsortChanging(System.Nullable<int> value);
    partial void OnsortChanged();
    partial void Onview_amountChanging(System.Nullable<int> value);
    partial void Onview_amountChanged();
    partial void Onbuy_amountChanging(System.Nullable<int> value);
    partial void Onbuy_amountChanged();
    partial void Ondate_addedChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_addedChanged();
    partial void Onlast_modifiedChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_modifiedChanged();
    partial void OntitileChanging(string value);
    partial void OntitileChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnkeywordChanging(string value);
    partial void OnkeywordChanged();
    #endregion
		
		public tbl_item()
		{
			this._tbl_item_category = default(EntityRef<tbl_item_category>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent", DbType="Int")]
		public System.Nullable<int> parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					if (this._tbl_item_category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnparentChanging(value);
					this.SendPropertyChanging();
					this._parent = value;
					this.SendPropertyChanged("parent");
					this.OnparentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detail_short", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string detail_short
		{
			get
			{
				return this._detail_short;
			}
			set
			{
				if ((this._detail_short != value))
				{
					this.Ondetail_shortChanging(value);
					this.SendPropertyChanging();
					this._detail_short = value;
					this.SendPropertyChanged("detail_short");
					this.Ondetail_shortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detail", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string detail
		{
			get
			{
				return this._detail;
			}
			set
			{
				if ((this._detail != value))
				{
					this.OndetailChanging(value);
					this.SendPropertyChanging();
					this._detail = value;
					this.SendPropertyChanged("detail");
					this.OndetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="VarChar(255)")]
		public string subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this.OnsubjectChanging(value);
					this.SendPropertyChanging();
					this._subject = value;
					this.SendPropertyChanged("subject");
					this.OnsubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="BigInt")]
		public System.Nullable<long> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_promotion_price", DbType="BigInt")]
		public System.Nullable<long> promotion_price
		{
			get
			{
				return this._promotion_price;
			}
			set
			{
				if ((this._promotion_price != value))
				{
					this.Onpromotion_priceChanging(value);
					this.SendPropertyChanging();
					this._promotion_price = value;
					this.SendPropertyChanged("promotion_price");
					this.Onpromotion_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(255)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hot", DbType="TinyInt")]
		public System.Nullable<byte> hot
		{
			get
			{
				return this._hot;
			}
			set
			{
				if ((this._hot != value))
				{
					this.OnhotChanging(value);
					this.SendPropertyChanging();
					this._hot = value;
					this.SendPropertyChanged("hot");
					this.OnhotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort", DbType="Int")]
		public System.Nullable<int> sort
		{
			get
			{
				return this._sort;
			}
			set
			{
				if ((this._sort != value))
				{
					this.OnsortChanging(value);
					this.SendPropertyChanging();
					this._sort = value;
					this.SendPropertyChanged("sort");
					this.OnsortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_view_amount", DbType="Int")]
		public System.Nullable<int> view_amount
		{
			get
			{
				return this._view_amount;
			}
			set
			{
				if ((this._view_amount != value))
				{
					this.Onview_amountChanging(value);
					this.SendPropertyChanging();
					this._view_amount = value;
					this.SendPropertyChanged("view_amount");
					this.Onview_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buy_amount", DbType="Int")]
		public System.Nullable<int> buy_amount
		{
			get
			{
				return this._buy_amount;
			}
			set
			{
				if ((this._buy_amount != value))
				{
					this.Onbuy_amountChanging(value);
					this.SendPropertyChanging();
					this._buy_amount = value;
					this.SendPropertyChanged("buy_amount");
					this.Onbuy_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_added", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_added
		{
			get
			{
				return this._date_added;
			}
			set
			{
				if ((this._date_added != value))
				{
					this.Ondate_addedChanging(value);
					this.SendPropertyChanging();
					this._date_added = value;
					this.SendPropertyChanged("date_added");
					this.Ondate_addedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_modified", DbType="DateTime")]
		public System.Nullable<System.DateTime> last_modified
		{
			get
			{
				return this._last_modified;
			}
			set
			{
				if ((this._last_modified != value))
				{
					this.Onlast_modifiedChanging(value);
					this.SendPropertyChanging();
					this._last_modified = value;
					this.SendPropertyChanged("last_modified");
					this.Onlast_modifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titile", DbType="NVarChar(255)")]
		public string titile
		{
			get
			{
				return this._titile;
			}
			set
			{
				if ((this._titile != value))
				{
					this.OntitileChanging(value);
					this.SendPropertyChanging();
					this._titile = value;
					this.SendPropertyChanged("titile");
					this.OntitileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(255)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keyword", DbType="VarChar(255)")]
		public string keyword
		{
			get
			{
				return this._keyword;
			}
			set
			{
				if ((this._keyword != value))
				{
					this.OnkeywordChanging(value);
					this.SendPropertyChanging();
					this._keyword = value;
					this.SendPropertyChanged("keyword");
					this.OnkeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_item_category_tbl_item", Storage="_tbl_item_category", ThisKey="parent", OtherKey="id", IsForeignKey=true)]
		public tbl_item_category tbl_item_category
		{
			get
			{
				return this._tbl_item_category.Entity;
			}
			set
			{
				tbl_item_category previousValue = this._tbl_item_category.Entity;
				if (((previousValue != value) 
							|| (this._tbl_item_category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_item_category.Entity = null;
						previousValue.tbl_items.Remove(this);
					}
					this._tbl_item_category.Entity = value;
					if ((value != null))
					{
						value.tbl_items.Add(this);
						this._parent = value.id;
					}
					else
					{
						this._parent = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_item_category");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_item_category")]
	public partial class tbl_item_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private System.Nullable<int> _parent;
		
		private string _detail_short;
		
		private string _subject;
		
		private string _image;
		
		private System.Nullable<byte> _status;
		
		private System.Nullable<byte> _hot;
		
		private System.Nullable<int> _sort;
		
		private System.Nullable<System.DateTime> _date_added;
		
		private System.Nullable<System.DateTime> _last_modified;
		
		private string _titile;
		
		private string _description;
		
		private string _keyword;
		
		private EntitySet<tbl_item> _tbl_items;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnparentChanging(System.Nullable<int> value);
    partial void OnparentChanged();
    partial void Ondetail_shortChanging(string value);
    partial void Ondetail_shortChanged();
    partial void OnsubjectChanging(string value);
    partial void OnsubjectChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnstatusChanging(System.Nullable<byte> value);
    partial void OnstatusChanged();
    partial void OnhotChanging(System.Nullable<byte> value);
    partial void OnhotChanged();
    partial void OnsortChanging(System.Nullable<int> value);
    partial void OnsortChanged();
    partial void Ondate_addedChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_addedChanged();
    partial void Onlast_modifiedChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_modifiedChanged();
    partial void OntitileChanging(string value);
    partial void OntitileChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnkeywordChanging(string value);
    partial void OnkeywordChanged();
    #endregion
		
		public tbl_item_category()
		{
			this._tbl_items = new EntitySet<tbl_item>(new Action<tbl_item>(this.attach_tbl_items), new Action<tbl_item>(this.detach_tbl_items));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent", DbType="Int")]
		public System.Nullable<int> parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					this.OnparentChanging(value);
					this.SendPropertyChanging();
					this._parent = value;
					this.SendPropertyChanged("parent");
					this.OnparentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_detail_short", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string detail_short
		{
			get
			{
				return this._detail_short;
			}
			set
			{
				if ((this._detail_short != value))
				{
					this.Ondetail_shortChanging(value);
					this.SendPropertyChanging();
					this._detail_short = value;
					this.SendPropertyChanged("detail_short");
					this.Ondetail_shortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="VarChar(255)")]
		public string subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this.OnsubjectChanging(value);
					this.SendPropertyChanging();
					this._subject = value;
					this.SendPropertyChanged("subject");
					this.OnsubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(255)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="TinyInt")]
		public System.Nullable<byte> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hot", DbType="TinyInt")]
		public System.Nullable<byte> hot
		{
			get
			{
				return this._hot;
			}
			set
			{
				if ((this._hot != value))
				{
					this.OnhotChanging(value);
					this.SendPropertyChanging();
					this._hot = value;
					this.SendPropertyChanged("hot");
					this.OnhotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort", DbType="Int")]
		public System.Nullable<int> sort
		{
			get
			{
				return this._sort;
			}
			set
			{
				if ((this._sort != value))
				{
					this.OnsortChanging(value);
					this.SendPropertyChanging();
					this._sort = value;
					this.SendPropertyChanged("sort");
					this.OnsortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_added", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_added
		{
			get
			{
				return this._date_added;
			}
			set
			{
				if ((this._date_added != value))
				{
					this.Ondate_addedChanging(value);
					this.SendPropertyChanging();
					this._date_added = value;
					this.SendPropertyChanged("date_added");
					this.Ondate_addedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_modified", DbType="DateTime")]
		public System.Nullable<System.DateTime> last_modified
		{
			get
			{
				return this._last_modified;
			}
			set
			{
				if ((this._last_modified != value))
				{
					this.Onlast_modifiedChanging(value);
					this.SendPropertyChanging();
					this._last_modified = value;
					this.SendPropertyChanged("last_modified");
					this.Onlast_modifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titile", DbType="NVarChar(255)")]
		public string titile
		{
			get
			{
				return this._titile;
			}
			set
			{
				if ((this._titile != value))
				{
					this.OntitileChanging(value);
					this.SendPropertyChanging();
					this._titile = value;
					this.SendPropertyChanged("titile");
					this.OntitileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(255)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_keyword", DbType="VarChar(255)")]
		public string keyword
		{
			get
			{
				return this._keyword;
			}
			set
			{
				if ((this._keyword != value))
				{
					this.OnkeywordChanging(value);
					this.SendPropertyChanging();
					this._keyword = value;
					this.SendPropertyChanged("keyword");
					this.OnkeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_item_category_tbl_item", Storage="_tbl_items", ThisKey="id", OtherKey="parent")]
		public EntitySet<tbl_item> tbl_items
		{
			get
			{
				return this._tbl_items;
			}
			set
			{
				this._tbl_items.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_items(tbl_item entity)
		{
			this.SendPropertyChanging();
			entity.tbl_item_category = this;
		}
		
		private void detach_tbl_items(tbl_item entity)
		{
			this.SendPropertyChanging();
			entity.tbl_item_category = null;
		}
	}
}
#pragma warning restore 1591
