<?xml version="1.0" encoding="utf-8"?><Database Name="MyWebsite" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=MyWebsite;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MyWebsiteConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_admin" Member="tbl_admins">
    <Type Name="tbl_admin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="level_admin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_size" Member="tbl_sizes">
    <Type Name="tbl_size">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tbl_size_tbl_item_size" Member="tbl_item_sizes" ThisKey="id" OtherKey="id_size" Type="tbl_item_size" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_color" Member="tbl_colors">
    <Type Name="tbl_color">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="color_code" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tbl_color_tbl_item_color" Member="tbl_item_colors" ThisKey="id" OtherKey="id_color" Type="tbl_item_color" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_content" Member="tbl_contents">
    <Type Name="tbl_content">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="detail" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_images" Member="tbl_images">
    <Type Name="tbl_image">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="detail_short" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_item" Member="tbl_items">
    <Type Name="tbl_item">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="detail_short" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="detail" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="subject" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="price" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="promotion_price" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="hot" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="view_amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="buy_amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="keyword" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="tbl_item_tbl_item_color" Member="tbl_item_colors" ThisKey="id" OtherKey="id_product" Type="tbl_item_color" />
      <Association Name="tbl_item_tbl_item_size" Member="tbl_item_sizes" ThisKey="id" OtherKey="id_product" Type="tbl_item_size" />
      <Association Name="tbl_item_tbl_order_detail" Member="tbl_order_details" ThisKey="id" OtherKey="id_product" Type="tbl_order_detail" />
      <Association Name="tbl_item_category_tbl_item" Member="tbl_item_category" ThisKey="parent" OtherKey="id" Type="tbl_item_category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_item_category" Member="tbl_item_categories">
    <Type Name="tbl_item_category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="detail_short" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="subject" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="hot" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="keyword" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="tbl_item_category_tbl_item" Member="tbl_items" ThisKey="id" OtherKey="parent" Type="tbl_item" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_item_color" Member="tbl_item_colors">
    <Type Name="tbl_item_color">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_color" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_color_tbl_item_color" Member="tbl_color" ThisKey="id_color" OtherKey="id" Type="tbl_color" IsForeignKey="true" />
      <Association Name="tbl_item_tbl_item_color" Member="tbl_item" ThisKey="id_product" OtherKey="id" Type="tbl_item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_item_size" Member="tbl_item_sizes">
    <Type Name="tbl_item_size">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_size" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tbl_item_tbl_item_size" Member="tbl_item" ThisKey="id_product" OtherKey="id" Type="tbl_item" IsForeignKey="true" />
      <Association Name="tbl_size_tbl_item_size" Member="tbl_size" ThisKey="id_size" OtherKey="id" Type="tbl_size" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_member" Member="tbl_members">
    <Type Name="tbl_member">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="gender" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tbl_member_tbl_order" Member="tbl_orders" ThisKey="id" OtherKey="id_customer" Type="tbl_order" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_news" Member="tbl_news">
    <Type Name="tbl_new">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="detail_short" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="detail" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="subject" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="hot" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="view_amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="keyword" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="tbl_news_category_tbl_new" Member="tbl_news_category" ThisKey="parent" OtherKey="id" Type="tbl_news_category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_news_category" Member="tbl_news_categories">
    <Type Name="tbl_news_category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="detail_short" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="subject" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="hot" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="keyword" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="tbl_news_category_tbl_new" Member="tbl_news" ThisKey="id" OtherKey="parent" Type="tbl_new" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_order" Member="tbl_orders">
    <Type Name="tbl_order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name_customer" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="email_customer" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="address_customer" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="phone_customer" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="name_receiver" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="email_receiver" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="address_receiver" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="phone_receiver" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="total_amount" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tbl_order_tbl_order_detail" Member="tbl_order_details" ThisKey="id" OtherKey="id_order" Type="tbl_order_detail" />
      <Association Name="tbl_member_tbl_order" Member="tbl_member" ThisKey="id_customer" OtherKey="id" Type="tbl_member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_order_detail" Member="tbl_order_details">
    <Type Name="tbl_order_detail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="tbl_item_tbl_order_detail" Member="tbl_item" ThisKey="id_product" OtherKey="id" Type="tbl_item" IsForeignKey="true" />
      <Association Name="tbl_order_tbl_order_detail" Member="tbl_order" ThisKey="id_order" OtherKey="id" Type="tbl_order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_producer" Member="tbl_producers">
    <Type Name="tbl_producer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="detail_short" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="detail" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="subject" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="hot" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="sort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_shop_config" Member="tbl_shop_configs">
    <Type Name="tbl_shop_config">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="hotline" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="keyword" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_module" Member="tbl_modules">
    <Type Name="tbl_module">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_visible" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="name_partial" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="date_added" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="last_modified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tbl_support" Member="tbl_supports">
    <Type Name="tbl_support">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="yahoo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="skype" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>